version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
